version: '2'

services:
  # PostgreSQL database
  db:
     image: mdillon/postgis
     volumes:
       - .data/postgres:/var/lib/postgresql/data

  # Redis
  redis:
     image: redis
     volumes:
       - .data/redis:/data
 
  # Web Server
  small:
     build: .
     command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8501"
     links:
       - db
       - redis
     depends_on:
      - db
      - redis
     volumes:
      - .:/code
     ports:
      - "8501:8501"
     env_file: .env
     privileged: true


  # Celery worker
  celery:
     build: .
     command: bash -c "celery worker -A SMall.celery -l info"
     volumes:
       - .:/code
     links:
       - db
       - redis
     depends_on:
       - redis
