stages:
  - test
  - build
  - push_image
  - deploy_dev
  - deploy_production

before_script:
  - whoami
  - pwd
  - ls

cache:
  paths:
    - node_modules/

test:
  stage: test
  only:
    - develop
    - master
  script:
    - whoami
  tags:
    - shell

build:
  before_script:
    - docker ps -a
  stage: build
  only:
    - develop
    - master
  script:
    - docker build -t fe/merchant:`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD` .
    - docker images
  tags:
    - shell

push_image:
  stage: push_image
  only:
    - develop
    - master
  script:
    - docker tag fe/merchant:`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD` docker.speedx.com:5000/fe/merchant:`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD`
    - docker login docker.speedx.com:5000 -u speedx -p speedx2017
    - docker push docker.speedx.com:5000/fe/merchant:`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD`
    - docker logout docker.speedx.com:5000
  tags:
    - shell

deploy_dev:
  stage: deploy_dev
  only:
    - develop
  script:
    - a=`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD`
    - ansible web5 -ugitlab-runner -m shell -a "docker login docker.speedx.com:5000 -u speedx -p speedx2017"
    - ansible web5 -ugitlab-runner -m shell -a "docker pull docker.speedx.com:5000/fe/merchant:$a"
    - ansible web5 -ugitlab-runner -m shell -a "docker ps -qaf "name=merchant" | xargs docker rm -f"
    - ansible web5 -ugitlab-runner -m shell -a "docker run -d -p 3040:80 --name merchant --restart=always docker.speedx.com:5000/fe/merchant:$a" --sudo 
    - ansible web5 -ugitlab-runner -m shell -a "docker logout docker.speedx.com:5000"
  tags:
    - shell

deploy_production:
  stage: deploy_production
  only:
    - master
    - tags
  script:
     - a=`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD`
     - ansible web5 -ugitlab-runner -m shell -a "docker login docker.speedx.com:5000 -u speedx -p speedx2017"
     - ansible web5 -ugitlab-runner -m shell -a "docker pull docker.speedx.com:5000/fe/merchant:$a"
     - ansible web5 -ugitlab-runner -m shell -a "docker ps -aqf "name=merchant" | xargs docker rm -f"
     - ansible web5 -ugitlab-runner -m shell -a "docker run -d -p 3040:80 --name merchant --restart=always docker.speedx.com:5000/fe/merchant:$a" --sudo
     - ansible web5 -ugitlab-runner -m shell -a "docker logout docker.speedx.com:5000"
  tags:
    - shell
