stages:
  - test
  - build
  - push_image
  - deploy_dev
  - deploy_production

test:
  stage: test
  only:
    - develop
    - master
    - /^release-.*$/
  script:
    - whoami
  tags:
    - shell

build:
  stage: build
  only:
    - develop
    - master
    - /^release-.*$/
  script:
    - docker build -t backend/lehavre:`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD` .
    - docker images
  tags:
    - shell

push_image:
  stage: push_image
  only:
    - develop
    - master
    - /^release-.*$/
  script:
    - docker tag backend/lehavre:`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD` docker.speedx.com:5000/backend/lehavre:`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD`
    - docker login docker.speedx.com:5000 -u speedx -p speedx2017
    - docker push docker.speedx.com:5000/backend/lehavre:`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD`
    - docker logout docker.speedx.com:5000
  tags:
    - shell

deploy_dev:
  stage: deploy_dev
  only:
    - develop
  script:
    - a=`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD`
    - ansible web5 -ugitlab-runner -m shell -a "docker login docker.speedx.com:5000 -u speedx -p speedx2017"
    - ansible web5 -ugitlab-runner -m shell -a "docker pull docker.speedx.com:5000/backend/lehavre:$a"
    - ansible web5 -ugitlab-runner -m shell -a "docker ps -qaf "name=lehavre" | xargs docker rm -f"
    - ansible web5 -ugitlab-runner -m shell -a "docker run -d -p 8100:8100 --name lehavre --restart=always -e DJANGO_SETTINGS_MODULE=Lehavre.settings docker.speedx.com:5000/backend/lehavre:$a python manage.py runserver 0.0.0.0:8100" --sudo
    - ansible web5 -ugitlab-runner -m shell -a "docker logout docker.speedx.com:5000"
  tags:
    - shell

deploy_production:
  stage: deploy_production
  only:
    - /^release-.*$/
  except:
    - branches
  script:
    - a=`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD`
    - ansible web5 -ugitlab-runner -m shell -a "docker login docker.speedx.com:5000 -u speedx -p speedx2017"
    - ansible web5 -ugitlab-runner -m shell -a "docker pull docker.speedx.com:5000/backend/lehavre:$a"
    - ansible web5 -ugitlab-runner -m shell -a "docker ps -qaf "name=lehavre" | xargs docker rm -f"
    - ansible web5 -ugitlab-runner -m shell -a "docker run -d -p 8100:8100 --name lehavre --restart=always -e DJANGO_SETTINGS_MODULE=Lehavre.settings-production docker.speedx.com:5000/backend/lehavre:$a python manage.py runserver 0.0.0.0:8100" --sudo
    - ansible web5 -ugitlab-runner -m shell -a "docker logout docker.speedx.com:5000"
  tags:
    - shell

